# Reference for reshaping data

Here you go Claw, do this to the data and it should result in a new data frame you can throw into what you have created so far and you can play with it to find out what other insights you can.

In [2]:
# package for listing and algebra
import numpy as np

# package for data processing
import pandas as pd

# package for plots
import matplotlib.pyplot as plt
%matplotlib inline

# package for regression analysis
import statsmodels.api as sm
from math import sqrt
import os

# package for statistics

from scipy import stats
from scipy.stats import skew
from scipy.special import boxcox1p

# package for more plotting
import seaborn as sns

# import a specific color palette and style guide
color = sns.color_palette()
sns.set_style('darkgrid')

from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.model_selection import KFold
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split, cross_val_score

from IPython.display import display, FileLink

# Cool command to get rid of useless warning messages
import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn

In [3]:
# I will import the data using a csv importation

data = pd.read_csv("/Users/hunterromano/Desktop/BlackFriday.csv")

In [4]:
data_combined = data.groupby(by = ["User_ID", "Gender", "Age", "Occupation", "City_Category", 
                                   "Stay_In_Current_City_Years", "Marital_Status"], as_index=False) ["Purchase"].sum()

In [5]:
data_combined

,User_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Purchase
0,1000001,F,0-17,10,A,2,0,333481
1,1000002,M,55+,16,C,4+,0,810353
2,1000003,M,26-35,15,A,3,0,341635
3,1000004,M,46-50,7,B,2,1,205987
4,1000005,M,26-35,20,A,1,1,821001
5,1000006,F,51-55,9,A,1,0,379450
6,1000007,M,36-45,1,B,1,1,234427
7,1000008,M,26-35,12,C,4+,1,796545
8,1000009,M,26-35,17,C,0,0,593960
9,1000010,F,36-45,1,B,4+,1,2169486
10,1000011,F,26-35,1,C,1,0,556902
11,1000012,M,26-35,12,C,2,0,120801
12,1000013,M,46-50,1,C,3,1,713927
13,1000014,M,36-45,0,C,0,0,127629
14,1000015,M,26-35,7,A,1,0,1047124
15,1000016,F,36-45,0,C,0,1,150428
16,1000017,M,51-55,1,C,0,0,1425501
17,1000018,F,18-25,3,B,3,0,1978675
18,1000019,M,0-17,10,A,3,0,1457938
19,1000020,M,26-35,14,A,0,0,185747
20,1000021,M,18-25,16,B,0,0,126744
21,1000022,M,18-25,15,A,4+,0,1279678
22,1000023,M,36-45,0,B,3,1,1670998
23,1000024,F,26-35,7,A,3,1,720850
24,1000025,M,18-25,4,C,4+,0,534215
25,1000026,M,26-35,7,B,2,1,1606174
26,1000027,M,26-35,11,C,1,1,448562
27,1000028,F,26-35,1,C,2,1,516560
28,1000029,M,36-45,7,C,1,0,696201
29,1000030,F,36-45,7,C,3,0,260985
...,...,...,...,...,...,...,...,...
5861,1006011,M,36-45,15,C,3,0,1142042
5862,1006012,M,36-45,15,C,4+,1,127552
5863,1006013,F,26-35,20,C,3,0,609155
5864,1006014,M,46-50,1,C,0,1,479224
5865,1006015,F,26-35,9,B,1,0,255812
5866,1006016,M,46-50,1,B,1,1,3542344
5867,1006017,F,36-45,7,B,1,0,126398
5868,1006018,M,36-45,1,C,3,0,911951
5869,1006019,M,26-35,0,A,4+,0,503361
5870,1006020,M,51-55,16,A,1,1,374475
5871,1006021,M,26-35,12,B,2,1,670470
5872,1006022,M,26-35,17,C,4+,0,242077
5873,1006023,M,26-35,0,C,2,1,1092875
5874,1006024,M,26-35,12,A,0,1,749393
5875,1006025,F,26-35,1,B,1,0,985215
5876,1006026,M,36-45,6,C,1,1,441411
5877,1006027,M,18-25,4,C,1,1,256312
5878,1006028,M,18-25,4,A,4+,0,335351
5879,1006029,F,26-35,1,C,1,1,130969
5880,1006030,M,26-35,17,C,1,1,666530
5881,1006031,F,18-25,0,C,1,0,266795
5882,1006032,M,46-50,7,A,3,0,480614
5883,1006033,M,51-55,13,B,1,1,501475
5884,1006034,M,26-35,14,A,3,0,187070
5885,1006035,F,26-35,1,C,3,0,926272
5886,1006036,F,26-35,15,B,4+,1,3821666
5887,1006037,F,46-50,1,C,4+,0,1075037
5888,1006038,F,55+,1,C,2,0,80859
5889,1006039,F,46-50,0,B,4+,1,554504
5890,1006040,M,26-35,6,B,2,0,1562615

In [6]:
newdata = pd.DataFrame(data_combined)

In [7]:
newdata

,User_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Purchase
0,1000001,F,0-17,10,A,2,0,333481
1,1000002,M,55+,16,C,4+,0,810353
2,1000003,M,26-35,15,A,3,0,341635
3,1000004,M,46-50,7,B,2,1,205987
4,1000005,M,26-35,20,A,1,1,821001
5,1000006,F,51-55,9,A,1,0,379450
6,1000007,M,36-45,1,B,1,1,234427
7,1000008,M,26-35,12,C,4+,1,796545
8,1000009,M,26-35,17,C,0,0,593960
9,1000010,F,36-45,1,B,4+,1,2169486
10,1000011,F,26-35,1,C,1,0,556902
11,1000012,M,26-35,12,C,2,0,120801
12,1000013,M,46-50,1,C,3,1,713927
13,1000014,M,36-45,0,C,0,0,127629
14,1000015,M,26-35,7,A,1,0,1047124
15,1000016,F,36-45,0,C,0,1,150428
16,1000017,M,51-55,1,C,0,0,1425501
17,1000018,F,18-25,3,B,3,0,1978675
18,1000019,M,0-17,10,A,3,0,1457938
19,1000020,M,26-35,14,A,0,0,185747
20,1000021,M,18-25,16,B,0,0,126744
21,1000022,M,18-25,15,A,4+,0,1279678
22,1000023,M,36-45,0,B,3,1,1670998
23,1000024,F,26-35,7,A,3,1,720850
24,1000025,M,18-25,4,C,4+,0,534215
25,1000026,M,26-35,7,B,2,1,1606174
26,1000027,M,26-35,11,C,1,1,448562
27,1000028,F,26-35,1,C,2,1,516560
28,1000029,M,36-45,7,C,1,0,696201
29,1000030,F,36-45,7,C,3,0,260985
...,...,...,...,...,...,...,...,...
5861,1006011,M,36-45,15,C,3,0,1142042
5862,1006012,M,36-45,15,C,4+,1,127552
5863,1006013,F,26-35,20,C,3,0,609155
5864,1006014,M,46-50,1,C,0,1,479224
5865,1006015,F,26-35,9,B,1,0,255812
5866,1006016,M,46-50,1,B,1,1,3542344
5867,1006017,F,36-45,7,B,1,0,126398
5868,1006018,M,36-45,1,C,3,0,911951
5869,1006019,M,26-35,0,A,4+,0,503361
5870,1006020,M,51-55,16,A,1,1,374475
5871,1006021,M,26-35,12,B,2,1,670470
5872,1006022,M,26-35,17,C,4+,0,242077
5873,1006023,M,26-35,0,C,2,1,1092875
5874,1006024,M,26-35,12,A,0,1,749393
5875,1006025,F,26-35,1,B,1,0,985215
5876,1006026,M,36-45,6,C,1,1,441411
5877,1006027,M,18-25,4,C,1,1,256312
5878,1006028,M,18-25,4,A,4+,0,335351
5879,1006029,F,26-35,1,C,1,1,130969
5880,1006030,M,26-35,17,C,1,1,666530
5881,1006031,F,18-25,0,C,1,0,266795
5882,1006032,M,46-50,7,A,3,0,480614
5883,1006033,M,51-55,13,B,1,1,501475
5884,1006034,M,26-35,14,A,3,0,187070
5885,1006035,F,26-35,1,C,3,0,926272
5886,1006036,F,26-35,15,B,4+,1,3821666
5887,1006037,F,46-50,1,C,4+,0,1075037
5888,1006038,F,55+,1,C,2,0,80859
5889,1006039,F,46-50,0,B,4+,1,554504
5890,1006040,M,26-35,6,B,2,0,1562615

In [8]:
newdata.dtypes

User_ID                        int64
Gender                        object
Age                           object
Occupation                     int64
City_Category                 object
Stay_In_Current_City_Years    object
Marital_Status                 int64
Purchase                       int64
dtype: object

so new data frame is newdata - if errors occur it is usually because parenthenses copy word so just put those in again